import { useEffect, useState } from 'react';
import {
  BarChart, Bar, LineChart, Line, PieChart, Pie, Cell,
  XAxis, YAxis, Tooltip, ResponsiveContainer, AreaChart, Area
} from 'recharts';
import api from '../api';
import { TrendingUp, DollarSign, ShoppingBag, Users, ArrowUp, ArrowDown, Download } from 'lucide-react';

const COLORS = ['#185FA5', '#1D9E75', '#F2C94C', '#FF453A', '#BF5AF2', '#FF9500', '#30D158', '#0A84FF'];

const STATUS_COLORS = {
  pending: '#F2C94C', accepted: '#1D9E75', packing: '#0A84FF',
  dispatched: '#F2C94C', delivered: '#30D158', completed: '#30D158',
  invoice_uploaded: '#30D158', rejected: '#FF453A', auto_cancelled: '#FF9500',
};

const PERIODS = [
  { label: '1D',  days: 1 },
  { label: '7D',  days: 7 },
  { label: '30D', days: 30 },
  { label: '90D', days: 90 },
  { label: 'FY',  days: 'fy' },
];

function getPeriodCutoff(days) {
  const now = new Date();
  if (days === 'fy') {
    // Financial year: April 1 of current or previous year
    const fyStart = new Date(now.getMonth() >= 3 ? now.getFullYear() : now.getFullYear() - 1, 3, 1);
    return fyStart;
  }
  const cutoff = new Date(now);
  cutoff.setDate(cutoff.getDate() - days);
  return cutoff;
}

function downloadCSV(data, orders, periodLabel) {
  const now = new Date();
  const generatedAt = now.toLocaleString('en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
  const totalRevenue = data.totalRevenue || 0;
  const totalOrders = data.periodOrders?.length || 0;
  const avgOrder = totalOrders ? totalRevenue / totalOrders : 0;
  const completedOrders = data.statusData?.find(s => s.name === 'completed' || s.name === 'delivered')?.value || 0;
  const rejectedOrders = data.statusData?.find(s => s.name === 'rejected')?.value || 0;
  const conversionRate = totalOrders ? ((completedOrders / totalOrders) * 100).toFixed(1) : '0.0';

  const sep = () => ',,,,,,,\n';
  const section = (title) => `\n"━━━ ${title} ━━━",,,,,,\n`;
  const fmt = (n) => parseFloat(n || 0).toFixed(2);

  const periodStart = data.dailyData?.[0]?.date || 'N/A';
  const periodEnd = data.dailyData?.[data.dailyData.length - 1]?.date || 'N/A';
  const peakDay = data.dailyData?.reduce((a, b) => b.revenue > a.revenue ? b : a, { date: 'N/A', revenue: 0 });
  const peakMonth = data.monthlyData?.reduce((a, b) => b.revenue > a.revenue ? b : a, { month: 'N/A', revenue: 0 });

  let csv = '';

  // ── Cover ──
  csv += '"╔══════════════════════════════════════════╗",,,,,,\n';
  csv += '"║         VENDORNET B2B PLATFORM           ║",,,,,,\n';
  csv += '"║      Revenue & Analytics Report          ║",,,,,,\n';
  csv += '"╚══════════════════════════════════════════╝",,,,,,\n';
  csv += sep();
  csv += '"REPORT INFORMATION",,,,,,\n';
  csv += '"──────────────────────────────────────────",,,,,,\n';
  csv += `"Platform:","VendorNet B2B Marketplace","Website:","https://vendornet.in",,,\n`;
  csv += `"Portal:","Admin Dashboard","Contact:","admin@vendornet.in",,,\n`;
  csv += `"Report Title:","Revenue & Analytics Report","Report Type:","Financial Summary",,,\n`;
  csv += `"Report Period:","${periodLabel}","Date Range:","${periodStart} to ${periodEnd}",,,\n`;
  csv += `"Period Start Date:","${periodStart}","Period End Date:","${periodEnd}",,,\n`;
  csv += `"Generated On:","${generatedAt}","Time Zone:","IST (UTC+5:30)",,,\n`;
  csv += `"Generated By:","VendorNet Admin Portal","Classification:","Confidential & Proprietary",,,\n`;
  csv += sep();

  // ── Quick Stats Banner ──
  csv += '"QUICK STATISTICS SNAPSHOT",,,,,,\n';
  csv += '"──────────────────────────────────────────",,,,,,\n';
  csv += `"Total Revenue","₹${fmt(totalRevenue)}","Total Orders","${totalOrders}","Avg Order Value","₹${fmt(avgOrder)}"\n`;
  csv += `"Completion Rate","${conversionRate}%","Rejected Orders","${rejectedOrders}","Commission Earned","₹${fmt(data.commission?.total_commission)}"\n`;
  csv += `"New Retailers","${data.newRetailers}","New Wholesalers","${data.newWholesalers}","Peak Day","${peakDay.date} (₹${fmt(peakDay.revenue)})"\n`;
  csv += `"Peak Month","${peakMonth.month} (₹${fmt(peakMonth.revenue)})","Top Retailer","${data.topRetailers?.[0]?.name || 'N/A'}","Top Wholesaler","${data.wholesalerData?.[0]?.name || 'N/A'}"\n`;
  csv += sep();

  // ── Executive Summary ──
  csv += section('EXECUTIVE SUMMARY');
  csv += '"Metric","Value","Benchmark / Notes",,,,\n';
  csv += `"Total Revenue","₹${fmt(totalRevenue)}","For selected period (${periodLabel})",,,,\n`;
  csv += `"Total Orders","${totalOrders}","All order statuses included",,,,\n`;
  csv += `"Average Order Value","₹${fmt(avgOrder)}","Total Revenue / Total Orders",,,,\n`;
  csv += `"Completed Orders","${completedOrders}","Delivered + Completed statuses",,,,\n`;
  csv += `"Rejected / Cancelled","${rejectedOrders}","Rejected + Auto-cancelled",,,,\n`;
  csv += `"Completion Rate","${conversionRate}%","Completed Orders / Total Orders × 100",,,,\n`;
  csv += `"Commission Earned","₹${fmt(data.commission?.total_commission)}","Platform commission on invoices",,,,\n`;
  csv += `"New Retailers Registered","${data.newRetailers}","Joined during selected period",,,,\n`;
  csv += `"New Wholesalers Registered","${data.newWholesalers}","Joined during selected period",,,,\n`;
  csv += `"Peak Revenue Day","${peakDay.date}","₹${fmt(peakDay.revenue)} earned",,,,\n`;
  csv += `"Peak Revenue Month","${peakMonth.month}","₹${fmt(peakMonth.revenue)} earned",,,,\n`;
  csv += `"Top Retailer by Spend","${data.topRetailers?.[0]?.name || 'N/A'}","₹${fmt(data.topRetailers?.[0]?.revenue || 0)}",,,,\n`;
  csv += `"Top Wholesaler by Revenue","${data.wholesalerData?.[0]?.name || 'N/A'}","₹${fmt(data.wholesalerData?.[0]?.revenue || 0)}",,,,\n`;
  csv += sep();

  // ── Daily Revenue ──
  csv += section('DAILY REVENUE TREND');
  csv += '"Date","Revenue (₹)","No. of Orders","Avg Order Value (₹)","Cumulative Revenue (₹)",,\n';
  let cumulative = 0;
  data.dailyData.forEach(d => {
    cumulative += d.revenue;
    const avg = d.orders ? (d.revenue / d.orders).toFixed(2) : '0.00';
    csv += `"${d.date}","${fmt(d.revenue)}","${d.orders}","${avg}","${fmt(cumulative)}",,\n`;
  });
  csv += sep();

  // ── Monthly Revenue ──
  csv += section('MONTHLY REVENUE SUMMARY');
  csv += '"Month","Revenue (₹)","No. of Orders","Avg Order Value (₹)","Growth vs Prev Month (%)",,\n';
  data.monthlyData.forEach((d, i) => {
    const prev = i > 0 ? data.monthlyData[i - 1].revenue : 0;
    const growth = prev ? (((d.revenue - prev) / prev) * 100).toFixed(1) : 'N/A';
    const avg = d.orders ? (d.revenue / d.orders).toFixed(2) : '0.00';
    csv += `"${d.month}","${fmt(d.revenue)}","${d.orders}","${avg}","${growth}",,\n`;
  });
  csv += sep();

  // ── Order Status ──
  csv += section('ORDER STATUS BREAKDOWN');
  csv += '"Status","Count","% of Total Orders","Revenue Impact",,\n';
  data.statusData.forEach(s => {
    const pct = totalOrders ? ((s.value / totalOrders) * 100).toFixed(1) : '0.0';
    const impact = ['completed', 'delivered', 'invoice_uploaded'].includes(s.name) ? 'Positive' : ['rejected', 'auto_cancelled'].includes(s.name) ? 'Negative' : 'Neutral';
    csv += `"${s.name}","${s.value}","${pct}%","${impact}",,\n`;
  });
  csv += sep();

  // ── Top Retailers ──
  csv += section('TOP RETAILERS BY SPEND');
  csv += '"Rank","Retailer Name","Total Orders","Total Spend (₹)","Avg Order Value (₹)","% of Total Revenue",\n';
  data.topRetailers.forEach((r, i) => {
    const avg = r.orders ? (r.revenue / r.orders).toFixed(2) : '0.00';
    const pct = totalRevenue ? ((r.revenue / totalRevenue) * 100).toFixed(1) : '0.0';
    csv += `"${i + 1}","${r.name}","${r.orders}","${fmt(r.revenue)}","${avg}","${pct}%",\n`;
  });
  csv += sep();

  // ── Top Wholesalers ──
  csv += section('TOP WHOLESALERS BY REVENUE');
  csv += '"Rank","Wholesaler Name","Revenue Generated (₹)","% of Total Revenue",,\n';
  data.wholesalerData.forEach((w, i) => {
    const pct = totalRevenue ? ((w.revenue / totalRevenue) * 100).toFixed(1) : '0.0';
    csv += `"${i + 1}","${w.name}","${fmt(w.revenue)}","${pct}%",,\n`;
  });
  csv += sep();

  // ── All Orders ──
  csv += section('COMPLETE ORDER LEDGER');
  csv += '"Order ID","Retailer Name","Retailer Mobile","Amount (₹)","Status","Order Date","Time"\n';
  orders.forEach(o => {
    const d = new Date(o.created_at);
    const date = d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
    const time = d.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' });
    csv += `"${o.order_id}","${(o.retailer_name || '').replace(/"/g, '')}","${o.retailer_mobile || ''}","${fmt(o.total_amount)}","${o.overall_status || 'pending'}","${date}","${time}"\n`;
  });
  csv += sep();

  // ── Footer ──
  csv += '\n"Report generated by VendorNet Admin Portal",,,,,,\n';
  csv += `"© ${now.getFullYear()} VendorNet. Confidential & Proprietary.",,,,,,\n`;

  const BOM = '\uFEFF';
  const blob = new Blob([BOM + csv], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `VendorNet_Analytics_${periodLabel}_${now.toISOString().slice(0, 10)}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function Analytics() {
  const [data, setData] = useState(null);
  const [allOrders, setAllOrders] = useState([]);
  const [loading, setLoading] = useState(true);
  const [period, setPeriod] = useState(30);

  useEffect(() => { fetchData(); }, [period]);

  const fetchData = async () => {
    setLoading(true);
    try {
      const [ordersRes, commRes, usersRes] = await Promise.all([
        api.get('/admin/orders'),
        api.get('/admin/commission'),
        api.get('/admin/users'),
      ]);

      const orders = ordersRes.data.orders || [];
      const commission = commRes.data;
      const users = usersRes.data.users || [];

      setAllOrders(orders);

      const now = new Date();
      const cutoff = getPeriodCutoff(period);
      const prevDays = period === 'fy' ? 365 : period;
      const prevCutoff = new Date(cutoff);
      prevCutoff.setDate(prevCutoff.getDate() - prevDays);

      const periodOrders = orders.filter(o => new Date(o.created_at) >= cutoff);
      const prevOrders = orders.filter(o => new Date(o.created_at) >= prevCutoff && new Date(o.created_at) < cutoff);

      const totalRevenue = periodOrders.reduce((s, o) => s + parseFloat(o.total_amount || 0), 0);
      const prevRevenue = prevOrders.reduce((s, o) => s + parseFloat(o.total_amount || 0), 0);
      const revenueChange = prevRevenue ? ((totalRevenue - prevRevenue) / prevRevenue) * 100 : 0;

      const avgOrderValue = periodOrders.length ? totalRevenue / periodOrders.length : 0;
      const prevAvg = prevOrders.length ? prevOrders.reduce((s, o) => s + parseFloat(o.total_amount || 0), 0) / prevOrders.length : 0;
      const avgChange = prevAvg ? ((avgOrderValue - prevAvg) / prevAvg) * 100 : 0;
      const ordersChange = prevOrders.length ? ((periodOrders.length - prevOrders.length) / prevOrders.length) * 100 : 0;

      // Daily data
      const days = period === 'fy' ? Math.ceil((now - cutoff) / (1000 * 60 * 60 * 24)) : period === 1 ? 1 : period;
      const dayMap = {};
      for (let i = days - 1; i >= 0; i--) {
        const d = new Date(now);
        d.setDate(d.getDate() - i);
        const key = period === 1
          ? d.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })
          : d.toLocaleDateString('en-IN', { day: 'numeric', month: 'short' });
        dayMap[key] = { date: key, revenue: 0, orders: 0 };
      }
      periodOrders.forEach(o => {
        const key = period === 1
          ? new Date(o.created_at).toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })
          : new Date(o.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' });
        if (dayMap[key]) {
          dayMap[key].revenue += parseFloat(o.total_amount || 0);
          dayMap[key].orders += 1;
        }
      });
      const dailyData = Object.values(dayMap);

      // Monthly data (last 12 months for FY, else 6)
      const monthCount = period === 'fy' ? 12 : 6;
      const monthMap = {};
      for (let i = monthCount - 1; i >= 0; i--) {
        const d = new Date(now);
        d.setMonth(d.getMonth() - i);
        const key = d.toLocaleDateString('en-IN', { month: 'short', year: '2-digit' });
        monthMap[key] = { month: key, revenue: 0, orders: 0 };
      }
      orders.forEach(o => {
        const key = new Date(o.created_at).toLocaleDateString('en-IN', { month: 'short', year: '2-digit' });
        if (monthMap[key]) {
          monthMap[key].revenue += parseFloat(o.total_amount || 0);
          monthMap[key].orders += 1;
        }
      });
      const monthlyData = Object.values(monthMap);

      // Wholesaler revenue
      const wholesalerMap = {};
      periodOrders.forEach(o => {
        const name = o.wholesaler_name || 'Unknown';
        wholesalerMap[name] = (wholesalerMap[name] || 0) + parseFloat(o.total_amount || 0);
      });
      const wholesalerData = Object.entries(wholesalerMap)
        .map(([name, revenue]) => ({ name, revenue }))
        .sort((a, b) => b.revenue - a.revenue).slice(0, 8);

      // Status breakdown
      const statusMap = {};
      periodOrders.forEach(o => {
        const s = o.overall_status || 'pending';
        statusMap[s] = (statusMap[s] || 0) + 1;
      });
      const statusData = Object.entries(statusMap).map(([name, value]) => ({ name, value }));

      // Top retailers
      const retailerMap = {};
      periodOrders.forEach(o => {
        const name = o.retailer_name || 'Unknown';
        if (!retailerMap[name]) retailerMap[name] = { name, revenue: 0, orders: 0 };
        retailerMap[name].revenue += parseFloat(o.total_amount || 0);
        retailerMap[name].orders += 1;
      });
      const topRetailers = Object.values(retailerMap).sort((a, b) => b.revenue - a.revenue).slice(0, 5);

      const newUsers = users.filter(u => new Date(u.created_at) >= cutoff);
      const newRetailers = newUsers.filter(u => u.role?.includes('retailer')).length;
      const newWholesalers = newUsers.filter(u => u.role?.includes('wholesaler')).length;

      setData({
        totalRevenue, prevRevenue, revenueChange,
        avgOrderValue, avgChange,
        periodOrders, ordersChange,
        commission,
        dailyData, monthlyData,
        wholesalerData, statusData,
        topRetailers,
        newRetailers, newWholesalers,
      });
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const fmt = (n) => `₹${parseFloat(n || 0).toLocaleString('en-IN', { maximumFractionDigits: 0 })}`;

  const periodLabel = PERIODS.find(p => p.days === period)?.label || '';

  if (loading) return <Loader />;

  return (
    <div>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24, flexWrap: 'wrap', gap: 12 }}>
        <div>
          <h1 style={{ fontSize: 22, fontWeight: 700, color: '#0f172a', margin: 0 }}>Revenue Analytics</h1>
          <p style={{ fontSize: 13, color: '#64748b', margin: '4px 0 0' }}>Platform financial overview · {periodLabel}</p>
        </div>
        <div style={{ display: 'flex', gap: 8, alignItems: 'center' }}>
          {PERIODS.map(p => (
            <button key={p.label} onClick={() => setPeriod(p.days)}
              style={{ padding: '7px 14px', borderRadius: 8, border: '1px solid #e2e8f0', fontSize: 13, fontWeight: 500, cursor: 'pointer', background: period === p.days ? '#185FA5' : '#fff', color: period === p.days ? '#fff' : '#475569' }}>
              {p.label}
            </button>
          ))}
          <button onClick={() => downloadCSV(data, allOrders, periodLabel)}
            style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '7px 14px', borderRadius: 8, border: '1px solid #e2e8f0', fontSize: 13, fontWeight: 500, cursor: 'pointer', background: '#fff', color: '#475569', marginLeft: 4 }}>
            <Download size={14} /> Export CSV
          </button>
        </div>
      </div>

      {/* KPI Cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(190px, 1fr))', gap: 14, marginBottom: 24 }}>
        {[
          { label: 'Total Revenue',    value: fmt(data.totalRevenue),    change: data.revenueChange, icon: TrendingUp, color: '#185FA5', bg: '#e6f1fb' },
          { label: 'Total Orders',     value: data.periodOrders.length,  change: data.ordersChange,  icon: ShoppingBag, color: '#1D9E75', bg: '#e1f5ee' },
          { label: 'Avg Order Value',  value: fmt(data.avgOrderValue),   change: data.avgChange,     icon: DollarSign,  color: '#F2C94C', bg: '#faeeda' },
          { label: 'Commission',       value: fmt(data.commission.total_commission || 0), change: null, icon: DollarSign, color: '#BF5AF2', bg: '#f3e8ff' },
          { label: 'New Retailers',    value: data.newRetailers,         change: null,               icon: Users,       color: '#0A84FF', bg: '#e0f0ff' },
          { label: 'New Wholesalers',  value: data.newWholesalers,       change: null,               icon: Users,       color: '#FF9500', bg: '#fff3e0' },
        ].map((kpi, i) => (
          <div key={i} style={styles.kpiCard}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
              <div style={{ width: 38, height: 38, borderRadius: 10, background: kpi.bg, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                <kpi.icon size={18} color={kpi.color} />
              </div>
              {kpi.change !== null && (
                <span style={{ display: 'flex', alignItems: 'center', gap: 3, fontSize: 12, fontWeight: 600, color: kpi.change >= 0 ? '#16a34a' : '#dc2626' }}>
                  {kpi.change >= 0 ? <ArrowUp size={12} /> : <ArrowDown size={12} />}
                  {Math.abs(kpi.change).toFixed(1)}%
                </span>
              )}
            </div>
            <div style={{ fontSize: 22, fontWeight: 700, color: '#0f172a' }}>{kpi.value}</div>
            <div style={{ fontSize: 12, color: '#64748b', marginTop: 2 }}>{kpi.label}</div>
          </div>
        ))}
      </div>

      {/* Daily Revenue */}
      <div style={styles.chartCard}>
        <h3 style={styles.chartTitle}>
          {period === 1 ? 'Hourly Revenue — Today' : `Daily Revenue — ${periodLabel}`}
        </h3>
        <ResponsiveContainer width="100%" height={220}>
          <AreaChart data={data.dailyData}>
            <defs>
              <linearGradient id="revGrad" x1="0" y1="0" x2="0" y2="1">
                <stop offset="5%" stopColor="#185FA5" stopOpacity={0.15} />
                <stop offset="95%" stopColor="#185FA5" stopOpacity={0} />
              </linearGradient>
            </defs>
            <XAxis dataKey="date" tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false}
              interval={period >= 90 ? 6 : period >= 30 ? 3 : 0} />
            <YAxis tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false}
              tickFormatter={v => `₹${(v / 1000).toFixed(0)}K`} />
            <Tooltip formatter={(v) => [`₹${v.toLocaleString('en-IN')}`, 'Revenue']}
              contentStyle={{ borderRadius: 10, border: 'none', boxShadow: '0 4px 16px rgba(0,0,0,0.1)', fontSize: 13 }} />
            <Area dataKey="revenue" stroke="#185FA5" strokeWidth={2} fill="url(#revGrad)" dot={false} />
          </AreaChart>
        </ResponsiveContainer>
      </div>

      {/* Monthly + Status */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
        <div style={styles.chartCard}>
          <h3 style={styles.chartTitle}>Monthly Revenue — {period === 'fy' ? '12 months' : '6 months'}</h3>
          <ResponsiveContainer width="100%" height={200}>
            <BarChart data={data.monthlyData} barSize={24}>
              <XAxis dataKey="month" tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false} />
              <YAxis tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false}
                tickFormatter={v => `₹${(v / 1000).toFixed(0)}K`} />
              <Tooltip formatter={(v) => [`₹${v.toLocaleString('en-IN')}`, 'Revenue']}
                contentStyle={{ borderRadius: 10, border: 'none', fontSize: 13 }} />
              <Bar dataKey="revenue" fill="#185FA5" radius={[6, 6, 0, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div style={styles.chartCard}>
          <h3 style={styles.chartTitle}>Order Status Breakdown</h3>
          <ResponsiveContainer width="100%" height={200}>
            <PieChart>
              <Pie data={data.statusData} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={75}
                label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}
                labelLine={false} style={{ fontSize: 10 }}>
                {data.statusData.map((entry, i) => (
                  <Cell key={i} fill={STATUS_COLORS[entry.name] || COLORS[i % COLORS.length]} />
                ))}
              </Pie>
              <Tooltip contentStyle={{ borderRadius: 10, border: 'none', fontSize: 13 }} />
            </PieChart>
          </ResponsiveContainer>
        </div>
      </div>

      {/* Top Wholesalers + Top Retailers */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, marginBottom: 16 }}>
        <div style={styles.chartCard}>
          <h3 style={styles.chartTitle}>Top Wholesalers by Revenue</h3>
          <ResponsiveContainer width="100%" height={200}>
            <BarChart data={data.wholesalerData} layout="vertical" barSize={14}>
              <XAxis type="number" tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false}
                tickFormatter={v => `₹${(v / 1000).toFixed(0)}K`} />
              <YAxis dataKey="name" type="category" tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false} width={90} />
              <Tooltip formatter={(v) => [`₹${v.toLocaleString('en-IN')}`, 'Revenue']}
                contentStyle={{ borderRadius: 10, border: 'none', fontSize: 13 }} />
              <Bar dataKey="revenue" fill="#1D9E75" radius={[0, 6, 6, 0]} />
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div style={styles.chartCard}>
          <h3 style={styles.chartTitle}>Top Retailers by Spend</h3>
          <table style={{ width: '100%', borderCollapse: 'collapse' }}>
            <thead>
              <tr>
                {['Retailer', 'Orders', 'Total Spend'].map(h => (
                  <th key={h} style={{ padding: '8px 10px', fontSize: 11, fontWeight: 600, color: '#94a3b8', textAlign: 'left', borderBottom: '1px solid #f1f5f9' }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {data.topRetailers.map((r, i) => (
                <tr key={i} style={{ borderBottom: '1px solid #f8fafc' }}>
                  <td style={{ padding: '10px 10px', fontSize: 13, fontWeight: 500, color: '#0f172a' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <div style={{ width: 26, height: 26, borderRadius: '50%', background: `${COLORS[i]}20`, color: COLORS[i], display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 11, fontWeight: 700, flexShrink: 0 }}>
                        {i + 1}
                      </div>
                      {r.name}
                    </div>
                  </td>
                  <td style={{ padding: '10px 10px', fontSize: 13, color: '#64748b' }}>{r.orders}</td>
                  <td style={{ padding: '10px 10px', fontSize: 13, fontWeight: 600, color: '#185FA5' }}>{fmt(r.revenue)}</td>
                </tr>
              ))}
              {data.topRetailers.length === 0 && (
                <tr><td colSpan={3} style={{ padding: 24, textAlign: 'center', color: '#94a3b8', fontSize: 13 }}>No data for this period</td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Daily Orders */}
      <div style={styles.chartCard}>
        <h3 style={styles.chartTitle}>
          {period === 1 ? 'Hourly Orders — Today' : `Daily Orders — ${periodLabel}`}
        </h3>
        <ResponsiveContainer width="100%" height={180}>
          <LineChart data={data.dailyData}>
            <XAxis dataKey="date" tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false}
              interval={period >= 90 ? 6 : period >= 30 ? 3 : 0} />
            <YAxis tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false} allowDecimals={false} />
            <Tooltip contentStyle={{ borderRadius: 10, border: 'none', fontSize: 13 }} />
            <Line dataKey="orders" stroke="#1D9E75" strokeWidth={2} dot={false} name="Orders" />
          </LineChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}

function Loader() {
  return (
    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: '60vh' }}>
      <div style={{ width: 36, height: 36, border: '3px solid #e2e8f0', borderTopColor: '#185FA5', borderRadius: '50%', animation: 'spin 0.8s linear infinite' }} />
    </div>
  );
}

const styles = {
  kpiCard: { background: '#fff', borderRadius: 14, padding: 18, border: '1px solid #e2e8f0', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' },
  chartCard: { background: '#fff', borderRadius: 14, padding: '20px', border: '1px solid #e2e8f0', boxShadow: '0 1px 3px rgba(0,0,0,0.04)', marginBottom: 16 },
  chartTitle: { fontSize: 14, fontWeight: 600, color: '#0f172a', marginBottom: 16, marginTop: 0 },
};
